package factoryDesingPattern;

public enum PanelType {

	AUX_PANEL,
	BID_PANEL,
	FORGOT_PASS_PANEL,
	GENERAL_INFO_PANEL,
	IMAGE_PANEL,
	ITEM_INFO_PANEL,
	ITEM_PANEL,
	ITEM_REGISTER_PANEL,
	LIST_PANEL,
	LOGIN_PANEL,
	MAIN_PANEL,
	PRICE_PANEL,
	TAG_PANEL,
	USER_INFO_PANEL,
	USER_PERSONAL_INFO,
	USER_REGISTER_PANEL;
}
